# Generated by Django 3.2.5 on 2021-07-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Location', models.IntegerField(choices=[(1, 'Тульская'), (2, 'Дом'), (3, 'Питер'), (4, 'Долгопрудный'), (5, 'Сочи'), (6, 'Новосибирск')], default=1)),
                ('Status', models.IntegerField(choices=[(1, 'Создан'), (2, 'Сейчас идёт'), (3, 'Закончен'), (4, 'Отменён')], default=1)),
                ('Teachers', models.ManyToManyField(to='WebApp.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('CostInHour', models.FloatField()),
                ('Webinars', models.ManyToManyField(to='WebApp.Web')),
            ],
        ),
    ]
