# Generated by Django 3.2.5 on 2021-07-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CostInHour',
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostInHour', models.FloatField()),
                ('Teach_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebApp.teacher')),
                ('Web_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebApp.web')),
            ],
        ),
    ]
