# Generated by Django 3.2.5 on 2021-07-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20210722_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='CostInHour',
            field=models.FloatField(verbose_name='Стоимость вебинара'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='Course_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WebApp.course', verbose_name='ID курса'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='Teach_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='WebApp.teacher', verbose_name='ID преподавателя'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Name',
            field=models.CharField(max_length=40, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Webinars',
            field=models.ManyToManyField(to='WebApp.Web', verbose_name='Вебинары данного курса'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='FullName',
            field=models.CharField(max_length=50, verbose_name='ФИО преподавателя'),
        ),
        migrations.AlterField(
            model_name='web',
            name='Location',
            field=models.IntegerField(choices=[(1, 'Тульская'), (2, 'Дом'), (3, 'Питер'), (4, 'Долгопрудный'), (5, 'Сочи'), (6, 'Новосибирск')], default=1, verbose_name='Место проведения вебинара'),
        ),
        migrations.AlterField(
            model_name='web',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Создан'), (2, 'Сейчас идёт'), (3, 'Закончен'), (4, 'Отменён')], default=1, verbose_name='Статус вебинара'),
        ),
        migrations.AlterField(
            model_name='web',
            name='Time',
            field=models.DateTimeField(verbose_name='Дата и время проведения вебинара'),
        ),
    ]
